AWSTemplateFormatVersion: 2010-09-09
Description:  ADF CloudFormation Template (Initial S3 Bucket) for Master Account in us-east-1 and your default deployment region
Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 Bucket used to store initial resources"
  DeploymentAccountId:
    Type: String
    Description: "The ID of the Deployment Account that has already been created"
    Default: ''
Conditions:
  DeploymentAccountBucket: !Not [ !Equals [!Ref DeploymentAccountId, '']]
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: DeploymentAccountBucket
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:Get*
              - s3:List*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${DeploymentAccountId}:root"
              Service:
                - codebuild.amazonaws.com
                - lambda.amazonaws.com
                - cloudformation.amazonaws.com